version: '3'
services:
  blog:
    image: ghost:1-alpine # Especificamos o contexto, ou seja, a pasta onde está o Dockerfile.
    ports: # Especificamos as portas que serão expostas.
      - 2368:2368
    restart: always # Especificamos a política de restart do container.
    environment:
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=root
      - database__connection__database=ghost
    depends_on:
      - db
    networks:
      - my-network
  db:
    image: mysql:5.7.40
    environment:
      - MYSQL_ROOT_PASSWORD=root
      # MYSQL_DATABASE: ghost
      # MYSQL_USER: ghost
      # MYSQL_PASSWORD: ghost
    restart: always # Especificamos a política de restart do container.
    networks:
      - my-network
    volumes:
      - dados-do-banco:/var/lib/mysql

volumes:
  dados-do-banco:

networks:
  my-network: