version: '3'
services:
  frontend:
    build: frontend/ # Especificamos o contexto, ou seja, a pasta onde está o Dockerfile.
    ports: # Especificamos as portas que serão expostas.
      - 3000:3000
    restart: always # Especificamos a política de restart do container.
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/frontend/src
    networks:
      - rede-virtual-1
  backend:
    build: backend/ # Especificamos o contexto, ou seja, a pasta onde está o Dockerfile.
    ports:
      - 3001:3001
    restart: always # Especificamos a política de restart do container.
    environment:
      - DB_HOST=database
    depends_on:
      - database
    networks:
      - rede-virtual-1
      - rede-virtual-2
  database:
    image: betrybe/docker-compose-example-database:v1  # Especificamos a Imagem Docker diretamente.
    restart: always
    networks:
      - rede-virtual-2

volumes:
  dados-do-banco:

networks:
  rede-virtual-1:
  rede-virtual-2: